version: '3.8'
services:
  musicblocks:
    build: ./
    image: ghcr.io/sugarlabs/musicblocks:4.0.0-dev
    env_file:
      - ./env/development.env
    ports:
      - '8080:8080'
      - '8000:8000'
    volumes:
      - ./:/app/
    container_name: musicblocks-4.0.0-dev
    stdin_open: true
    tty: true
